== Terms and definitions

The key words MUST, MUST NOT, REQUIRED, SHALL, SHALL NOT, SHOULD, SHOULD NOT, RECOMMENDED, MAY and OPTIONAL in this document are to be interpreted as described in RFC 2119 and RFC 8174 when, and only when, they appear in all capitals.

CAWG trust configuration::
The set of accepted EKUs, with their accepted certificate policies and trust anchors, that a validator maintains for `cawg.x509.cose` signers, as defined in the CAWG identity assertion specification.

CAWG Trust List::
The list of trust anchor configurations published under this document for the `id-kp-documentSigning` EKU.

CAWG certificate policy::
The certificate policy defined in <<_cawg_certificate_policy>>, identified by the CAWG certificate policy OID.

CAWG member::
An organisation that is a participant in the Creator Assertions Working Group under the DIF CAWG Charter and Operating Addendum.
_(Open question: see <<_open_questions>>.)_

Trust anchor configuration::
An X.509 CA certificate together with optional `notBefore` and `notAfter` date/times limiting the period for which it is trusted, as in the C2PA technical specification.

List operator::
The body responsible for maintaining, signing and publishing the CAWG Trust List.

Participating CA::
A certification authority whose trust anchor is included in the CAWG Trust List.
